import { useEffect, useState } from "react";
import ContentSkeleton from "@/components/content-skeleton";
import SectionHeader from "@/components/section-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/context/auth-context";
import {
  getNotifications,
  markAllNotificationsReadRequest,
  markNotificationReadRequest
} from "@/lib/hireai-api";
import { formatRelativeDate } from "@/lib/format";

function NotificationsPage() {
  const { token } = useAuth();
  const [notifications, setNotifications] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isMarkingAll, setIsMarkingAll] = useState(false);

  async function refresh() {
    const response = await getNotifications(token);
    setNotifications(response.items);
  }

  useEffect(() => {
    setIsLoading(true);
    refresh().catch(console.error).finally(() => setIsLoading(false));
  }, [token]);

  if (isLoading) {
    return <ContentSkeleton cards={1} detail={false} />;
  }

  return (
    <div className="space-y-6">
      <SectionHeader
        eyebrow="Notifications"
        title="Team activity and mentions"
        description="Track mention alerts, interview scheduling events, and workflow updates generated by collaboration actions."
        actions={
          <Button
            variant="secondary"
            onClick={async () => {
              const previous = notifications;
              setIsMarkingAll(true);
              setNotifications((current) =>
                current.map((item) => ({
                  ...item,
                  readAt: item.readAt || new Date().toISOString()
                }))
              );
              try {
                await markAllNotificationsReadRequest(token);
                await refresh();
              } catch (error) {
                console.error(error);
                setNotifications(previous);
              } finally {
                setIsMarkingAll(false);
              }
            }}
            disabled={isMarkingAll}
          >
            {isMarkingAll ? "Updating..." : "Mark all read"}
          </Button>
        }
      />

      <Card>
        <CardHeader>
          <CardTitle>Inbox</CardTitle>
          <CardDescription>Unread and recent system-generated activity for your account.</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-3">
          {notifications.map((notification) => (
            <button
              key={notification._id}
              type="button"
              onClick={async () => {
                if (!notification.readAt) {
                  const previous = notifications;
                  setNotifications((current) =>
                    current.map((item) =>
                      item._id === notification._id
                        ? { ...item, readAt: new Date().toISOString() }
                        : item
                    )
                  );
                  try {
                    await markNotificationReadRequest(token, notification._id);
                  } catch (error) {
                    console.error(error);
                    setNotifications(previous);
                  }
                }
              }}
              className={`rounded-[24px] border px-4 py-4 text-left transition ${
                notification.readAt
                  ? "border-border/80 bg-secondary/35"
                  : "border-primary/35 bg-primary/10"
              }`}
            >
              <div className="flex items-center justify-between gap-3">
                <div className="font-medium text-foreground">{notification.title}</div>
                <div className="text-xs text-muted-foreground">
                  {formatRelativeDate(notification.createdAt)}
                </div>
              </div>
              <p className="mt-2">{notification.message}</p>
            </button>
          ))}
          {!notifications.length ? (
            <div className="rounded-[24px] border border-dashed border-border/80 px-4 py-12 text-center text-sm text-muted-foreground">
              No notifications yet.
            </div>
          ) : null}
        </CardContent>
      </Card>
    </div>
  );
}

export default NotificationsPage;
